foq_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        mclowd_website:
            client: default    
            types:
                task:
                    mappings:
                        name: { boost: 5, analyzer: snowball }
                        description: { boost: 2, analyzer: snowball }
                        type: { analyzer: keyword }
                        currency: {analyzer: keyword}
                        categoryId: ~
                        budgetId: ~
                        createdAt: {type: date}
                        isActive: {type: boolean}
                        timePeriod: {analyzer: keyword}

                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model: App\Entity\Task
                        provider: ~    
                        finder: ~
                        listener: ~