knp_gaufrette:
    adapters:
        asset_adapter:
            local:
                directory: %kernel.root_dir%/../web/uploads/assets

    filesystems:
        asset_fs:
            adapter:    asset_adapter