admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin    

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

app:
    resource: "@App/Resources/config/routing.yml"
    type:     "rad_convention"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"    

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

mc_user:
    resource: "@MCUserBundle/Resources/config/routing.yml"    

mc_admin:
    resource: '@MCAdminBundle/Resources/config/routing.yml'
    prefix: /admin

mc_asset:
    resource: '@MCAssetBundle/Resources/config/routing/routing.yml'

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /messages

