security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, fos_facebook_provider]
        fos_userbundle:
            id: fos_user.user_provider.username
        fos_facebook_provider:
            id: mc_user.user_provider.facebook

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            switch_user:        true
            context:            user
            pattern:            /admin(.*)
            form_login:
                provider:       fos_userbundle
                login_path:     admin_security_login
                check_path:     admin_security_check
                failure_path:   null
                default_target_path: sonata_admin_dashboard
            logout:
                path:           admin_security_logout
                target: sonata_admin_dashboard
            anonymous:    true    

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            fos_facebook:
                app_url: "%api_facebook_name%"
                server_url: "%api_facebook_server%"
                login_path: fos_user_security_login
                check_path: /login_facebook_check
                redirect_to_facebook_login: false
                provider: fos_facebook_provider
            logout: true
            anonymous:    true


        secured_area:
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                    my_custom_provider: "/login/check-custom"
                    my_github:          "/login/check-github"
                login_path:        /login
                failure_path:      /login

                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/client, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        #admin area
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }