// Generated by CoffeeScript 1.4.0
(function() {
  var RemoteLink;

  RemoteLink = (function() {

    function RemoteLink() {
      var self;
      self = this;
      $(document).delegate('a[data-method], a[data-confirm]', 'click', function(e) {
        var confirm_message, data, href, link, method;
        e.preventDefault();
        link = $(this);
        method = link.data('method');
        data = link.data('params');
        href = link.attr('href');
        confirm_message = link.data('confirm');
        if (!confirm_message) {
          confirm_message = 'Are You sure?';
        }
        if (link.data('confirm')) {
          if (!self.confirm_message(confirm_message)) {
            return false;
          }
          return self.handleRequest(href, method);
        } else {
          return self.handleRequest(href, method);
        }
      });
    }

    RemoteLink.prototype.confirm_message = function(message) {
      return confirm(message);
    };

    RemoteLink.prototype.handleRequest = function(url, method) {
      var form, metadata_input;
      form = $('<form method="post" action="' + url + '"></form>');
      metadata_input = '<input name="_method" value="' + method + '" type="hidden" />';
      form.hide().append(metadata_input).appendTo('body');
      return form.submit();
    };

    return RemoteLink;

  })();

  window.RemoteLink = RemoteLink;

  jQuery(function() {
    return new RemoteLink;
  });

}).call(this);
