parameters:
    mc.asset.form.type.class: MC\AssetBundle\Form\Type\UploadType
    mc.asset.entity_class:    MC\AssetBundle\Entity\Asset

services:
    form.type.upload:
        class: %mc.asset.form.type.class%        
        tags:
            - { name: form.type, alias: upload }
        calls:
            - [ setContainer, [ @service_container ] ]

    mc.asset_manager:
        class: MC\AssetBundle\Model\AssetManager
        arguments: [ "@knp_gaufrette.filesystem_map", "@doctrine.orm.entity_manager", "@event_dispatcher", "asset_fs" ]

    mc.asset.asset_thumbnails_listener:
        class:     MC\AssetBundle\EventListener\AssetThumbnailsEventListener
        arguments: ["@imagine", "@imagine.filter.manager", "%imagine.filters%", "%kernel.root_dir%/../web"]
        tags:
            - { name:kernel.event_listener, event: mc.asset.events.asset_uploaded, method: onAssetUploadedEvent }