#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'runit'
cookbook 'nginx', :git => 'git://github.com/opscode-cookbooks/nginx.git'
cookbook 'php-fpm'
cookbook 'beanstalkd', :git => 'git://github.com/escapestudios/chef-beanstalkd.git'
cookbook 'mysql'
cookbook 'xml'