admin_security_login:
    pattern:  /login
    defaults: { _controller: MCAdminBundle:Security:login }

admin_security_check:
    pattern:  /login_check
    defaults: { _controller: MCAdminBundle:Security:check }

admin_security_logout:
    pattern:  /logout
    defaults: { _controller: MCAdminBundle:Security:logout }

