client_registration:
    pattern:  /register/client
    defaults: { _controller: MCUserBundle:Registration:registerClient }

contractor_registration:
    pattern:  /register/contractor
    defaults: { _controller: MCUserBundle:Registration:registerContractor }

registration_validation:
    pattern: /register/validate/{what}
    defaults: { _controller: MCUserBundle:Registration:validate }