client_registration:
    pattern:  /register/client
    defaults: { _controller: MCUserBundle:Registration:registerClient }

contractor_registration:
    pattern:  /register/contractor
    defaults: { _controller: MCUserBundle:Registration:registerContractor }

registration_validation:
    pattern: /register/validate/{what}
    defaults: { _controller: MCUserBundle:Registration:validate }

contractor_edit:
    pattern:  /contractor/edit
    defaults: { _controller: MCUserBundle:Contractor:edit }

contractor_update_city:
    pattern:  /contractor/update-city
    defaults: { _controller: MCUserBundle:Contractor:updateCity }
    requirements:
        _method:  POST
    options:
        expose: true

contractor_update_tag_line:
    pattern:  /contractor/update-tag-line
    defaults: { _controller: MCUserBundle:Contractor:updateTagLine }
    requirements:
        _method:  POST
    options:
        expose: true

contractor_update_fullname:
    pattern:  /contractor/update-fullname
    defaults: { _controller: MCUserBundle:Contractor:updateFullname }
    requirements:
        _method:  POST
    options:
        expose: true

contractor_update_overview:
    pattern:  /contractor/update-overview
    defaults: { _controller: MCUserBundle:Contractor:updateOverview }
    requirements:
        _method:  POST
    options:
        expose: true

contrator_add_employment:
    pattern:  /contractor/employment
    defaults: { _controller: MCUserBundle:Contractor:addEmployment, _format: json }
    requirements:
        _method:  POST
        _format:  json

contrator_remove_employment:
    pattern:  /contractor/employment/{id}
    defaults: { _controller: MCUserBundle:Contractor:removeEmployment, _format: json }
    requirements:
        _method:  DELETE
        _format:  json


contrator_add_education:
    pattern:  /contractor/education
    defaults: { _controller: MCUserBundle:Contractor:addEducation, _format: json }
    requirements:
        _method:  POST
        _format:  json

contrator_remove_education:
    pattern:  /contractor/education/{id}
    defaults: { _controller: MCUserBundle:Contractor:removeEducation, _format: json }
    requirements:
        _method:  DELETE
        _format:  json

contrator_add_contractor_task:
    pattern:  /contractor/contractor-tasks
    defaults: { _controller: MCUserBundle:Contractor:addContractorTask, _format: json }
    requirements:
        _method:  POST
        _format:  json

contrator_remove_contractor_task:
    pattern:  /contractor/contractor-tasks/{id}
    defaults: { _controller: MCUserBundle:Contractor:removeContractorTask, _format: json }
    requirements:
        _method:  DELETE
        _format:  json