contractor_index:
    pattern:  /contractors
    defaults: { _controller: MCUserBundle:Contractor:index }

contractor_profile:
    pattern:  /contractors/{id}
    defaults: { _controller: MCUserBundle:Contractor:profile }

client_registration:
    pattern:  /register/client
    defaults: { _controller: MCUserBundle:Registration:registerClient }
    
client_settings:
    pattern:  /client/settings
    defaults: { _controller: MCUserBundle:Client:settings }
    
client_update_fullname:
    pattern:  /client/update-fullname
    defaults: { _controller: MCUserBundle:Client:updateFullname }
    requirements:
        _method:  POST
    options:
        expose: true
        
client_update_password:
    pattern:  /client/update-password
    defaults: { _controller: MCUserBundle:Client:updatePassword }
    requirements:
        _method:  POST
    options:
        expose: true
        
client_update_phone:
    pattern:  /client/update-phone
    defaults: { _controller: MCUserBundle:Client:updatePhone }
    requirements:
        _method:  POST
    options:
        expose: true
        
client_update_email:
    pattern:  /client/update-email
    defaults: { _controller: MCUserBundle:Client:updateEmail }
    requirements:
        _method:  POST
    options:
        expose: true

contractor_registration:
    pattern:  /register/contractor
    defaults: { _controller: MCUserBundle:Registration:registerContractor }

registration_validation:
    pattern: /register/validate/{what}
    defaults: { _controller: MCUserBundle:Registration:validate }

contractor_edit:
    pattern:  /contractor/edit
    defaults: { _controller: MCUserBundle:Contractor:edit }
    
contractor_settings:
    pattern:  /contractor/settings
    defaults: { _controller: MCUserBundle:Contractor:settings }

contractor_update_city:
    pattern:  /contractor/update-city
    defaults: { _controller: MCUserBundle:Contractor:updateCity }
    requirements:
        _method:  POST
    options:
        expose: true

contractor_update_tag_line:
    pattern:  /contractor/update-tag-line
    defaults: { _controller: MCUserBundle:Contractor:updateTagLine }
    requirements:
        _method:  POST
    options:
        expose: true

contractor_update_fullname:
    pattern:  /contractor/update-fullname
    defaults: { _controller: MCUserBundle:Contractor:updateFullname }
    requirements:
        _method:  POST
    options:
        expose: true
        
contractor_update_password:
    pattern:  /contractor/update-password
    defaults: { _controller: MCUserBundle:Contractor:updatePassword }
    requirements:
        _method:  POST
    options:
        expose: true
        
contractor_update_phone:
    pattern:  /contractor/update-phone
    defaults: { _controller: MCUserBundle:Contractor:updatePhone }
    requirements:
        _method:  POST
    options:
        expose: true
        
contractor_update_email:
    pattern:  /contractor/update-email
    defaults: { _controller: MCUserBundle:Contractor:updateEmail }
    requirements:
        _method:  POST
    options:
        expose: true

contractor_update_overview:
    pattern:  /contractor/update-overview
    defaults: { _controller: MCUserBundle:Contractor:updateOverview }
    requirements:
        _method:  POST
    options:
        expose: true

contrator_add_employment:
    pattern:  /contractor/employment
    defaults: { _controller: MCUserBundle:Contractor:addEmployment, _format: json }
    requirements:
        _method:  POST
        _format:  json

contrator_remove_employment:
    pattern:  /contractor/employment/{id}
    defaults: { _controller: MCUserBundle:Contractor:removeEmployment, _format: json }
    requirements:
        _method:  DELETE
        _format:  json


contrator_add_education:
    pattern:  /contractor/education
    defaults: { _controller: MCUserBundle:Contractor:addEducation, _format: json }
    requirements:
        _method:  POST
        _format:  json

contrator_remove_education:
    pattern:  /contractor/education/{id}
    defaults: { _controller: MCUserBundle:Contractor:removeEducation, _format: json }
    requirements:
        _method:  DELETE
        _format:  json

contrator_add_contractor_task:
    pattern:  /contractor/contractor-tasks
    defaults: { _controller: MCUserBundle:Contractor:addContractorTask, _format: json }
    requirements:
        _method:  POST
        _format:  json

contrator_remove_contractor_task:
    pattern:  /contractor/contractor-tasks/{id}
    defaults: { _controller: MCUserBundle:Contractor:removeContractorTask, _format: json }
    requirements:
        _method:  DELETE
        _format:  json

contrator_add_qualification:
    pattern:  /contractor/qualification
    defaults: { _controller: MCUserBundle:Contractor:addQualification, _format: json }
    requirements:
        _method:  POST
        _format:  json

contrator_remove_qualification:
    pattern:  /contractor/qualification/{id}
    defaults: { _controller: MCUserBundle:Contractor:removeQualification, _format: json }
    requirements:
        _method:  DELETE
        _format:  json

social_register_choose_account:
    pattern: /social/choose_account
    defaults: { _controller: MCUserBundle:SocialRegistration:chooseAccountType }

social_register_client_account:
    pattern: /social/client
    defaults: { _controller: MCUserBundle:SocialRegistration:registerClientAccount }

social_register_contractor_account:
    pattern: /social/contractor
    defaults: { _controller: MCUserBundle:SocialRegistration:registerContractorAccount }


# fos_facebook integration
_fos_facebook_security_check:
  pattern:  /login_facebook_check

_fos_facebook_security_logout:
  pattern:  /logout