# https://github.com/KnpLabs/geekweek12/wiki/Routing

homepage:
    pattern: /
    defaults: { _controller: FrameworkBundle:Template:template, template: 'App::homepage.html.twig' }

settings:
    pattern: /admin/settings
    defaults: { _controller: App:Settings:list, template: 'App:Settings:list.html.twig'}

App:Tasks: 
    resources:
        show: 
            pattern: /{id}/{slug}

App:Tasks:my: /tasks/my

App:Proposals: ~
App:Settings: ~