# https://github.com/KnpLabs/geekweek12/wiki/Routing

homepage:
    pattern: /
#    defaults: { _controller: FrameworkBundle:Template:template, template: 'App::homepage.html.twig' }
    defaults: { _controller: App:Home:index}

settings:
    pattern: /admin/settings
    defaults: { _controller: App:Settings:list, template: 'App:Settings:list.html.twig'}

App:Tasks: ~
App:Tasks:my: /tasks/my
App:Tasks:show: /tasks/{id}/{slug}

App:Proposals: ~
App:Settings: ~

App:Profile:
    collections:
        index:
            requirements: {_method: "GET|POST"}
