# http://symfony.com/doc/current/components/dependency_injection/index.html
services:
    app.behavours.ownable:
        class:   "App\Behaviours\OwnableListener"
        public:  false
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_subscriber }
    app.services.settings:
        class:      "App\Services\Settings"
        public:     true
        arguments:  ['@doctrine.orm.entity_manager']
        calls:
            - [setFormFactory, ['@form.factory']]
            - [setNotificationServer, ['%notifications_server%','%notifications_port%']]
            
    app.services.notifications:
        class:      "App\Services\Notifications"
        public:     true
        arguments: ['%notifications_server%','%notifications_port%']

    app.services.mailer:
        class:      "App\Services\MailerService"
        public:     true
        arguments: ['@mailer', '@twig', '%mailer_from%']
